### PR TITLE
Set default parameters

### PR DESCRIPTION
**Pull request by hillelcoren**
We use the default parameters in our app (invoiceninja) to create the UI to set the credentials.

We're using the redirect gateway, if the values for the other gateways are different let me know and I'll move the code to RedirectGateway.php.

### CODE REVIEW

**Comment by joeHickson** [comment]
Hi Hillelcoren,
That seems sensible as a starting point in the abstract gateway. Please could you flick the test mode default bool - by default the driver currently generates as in test mode.
Travis is now failing this build - the core omnipay test is looking for a get / set method on each of the parameters - there is currently only a setAccessToken method, not a getAccessToken (probably my fault there). Would you mind adding the get method to the abstract gateway?

Thanks,

Joe

**Comment by hillelcoren** [comment]
Done

**Comment by joeHickson** [comment]
Hi Hillel,
I realised it needed adding to the abstract request too - I stuck them on and the unit tests were passing. All merged now. If you need a release just let me know, otherwise I'll assume you are happy developing off master for now.

Thanks

Joe

**Comment by hillelcoren** [comment]
How should the redirect gateway work? After submitting a payment I see the new customer in the GoCardless portal but I don't see the payment. 

Let me know if there's a better place for questions.

**Comment by joeHickson** [comment]
Probably as good a place as any!
The redirect flow should eventually return you a RedirectCompleteAuthoriseResponse object - this will contain a customer reference and a mandate reference. You then need to use the mandate reference to create the subscription.
e.g.
`$authoriseResponse = $completeAuthoriseRequest->send();
$subscriptionData = [
            'amount' => $this->subscriptionAmount,
            'currency' => $this->subscriptionCurrency,
            'subscriptionDayOfMonth' => $this->subscriptionDayOfMonth,
            'intervalCount' => $this->subscriptionIntervalCount,
            'interval' => $this->subscriptionInterval,
            'subscriptionMetaData' => $this->subscriptionMetaData,
            'subscriptionMonth' => null,
            'paymentDescription' => $this->subscriptionPaymentDescription,
            'statementDescriptor' => null,
            'paymentDate' => $this->subscriptionPaymentDate,
            'mandateReference' => $authoriseResponse->getMandateId(),
            'subscriptionCount' => $this->subscriptionCount,
        ];

$subscriptionResponse = $driver->createSubscription($subscriptionData)->send();`

There is a slight inconsistency in the naming - the redirect response object should probably have functions called getMandateReference and getCustomerReference rather than ID. Feel free to rename them - the redirect flow is still a working draft (we are using the pro gateway) so we can produce a 0.x versioned release once it is working for you guys.

**Comment by hillelcoren** [comment]
Thanks, that's very helpful!

**Comment by joeHickson** [comment]
You're welcome - the documentation is (unsurprisingly) lagging behind!

**Pull request merged**
